version: "3.3"
services:
  oracle:
    image: "switchboardlabs/node:${SBV2_ORACLE_VERSION:-dev-v2-07-18-22}" # https://hub.docker.com/r/switchboardlabs/node/tags
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - VERBOSE=1
      - LIVE=1
      - CLUSTER=${CLUSTER:-localnet}
      - HEARTBEAT_INTERVAL=30 # Seconds
      - ORACLE_KEY=5xKViQxAKcrN4o7RyPLPazb3uLcv2SPv3Bfm5TKmnb8q
    #  - RPC_URL=${RPC_URL}
secrets:
  PAYER_SECRETS:
    file: /root/.config/solana/id.json
